# data
training_file: data/rcv1/train.txt
test_file: data/rcv1/test.txt
data_name: rcv1
min_vocab_freq: 1
max_seq_length: 500
include_test_labels: false
remove_no_label_data: false
add_special_tokens: false

# train
seed: 1337
epochs: 50
batch_size: 64
optimizer: adam
learning_rate: ['grid_search', [0.001, 0.0005, 0.0001]]
momentum: 0.9
weight_decay: 0
patience: 5
shuffle: true

# eval
eval_batch_size: 256
monitor_metrics: ['Macro-F1', 'Micro-F1', 'P@1', 'P@3', 'P@5']
val_metric: Macro-F1

# model
model_name: KimCNN
multiclass: false
loss_function: binary_cross_entropy_with_logits
init_weight: kaiming_uniform
network_config:
  filter_sizes: ['grid_search', [[2,4,8], [4,6]]]
  embed_dropout: ['choice', [0, 0.2, 0.4, 0.6, 0.8]]
  encoder_dropout: ['choice', [0, 0.2, 0.4, 0.6, 0.8]]
  num_filter_per_size: 128 # filter channels
  activation: relu

# pretrained vocab / embeddings
embed_file: glove.6B.300d
vocab_file: null
normalize_embed: false

# hyperparamter search
search_alg: basic_variant
embed_cache_dir: .vector_cache
num_samples: 10 # run `2 (number of grid_search) * num_samples` trials
scheduler: null

# other parameters specified in main.py::get_args
checkpoint_path: null
cpu: false
data_workers: 4
eval: false
label_file: null
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
metric_threshold: 0.5
result_dir: runs
save_k_predictions: 0
silent: true
val_size: 0.2
