# data
training_file: data/rcv1/train.txt
test_file: data/rcv1/test.txt
data_name: rcv1
min_vocab_freq: 1
max_seq_length: 500

# train
seed: 1337
epochs: 50
batch_size: 64
optimizer: adam
learning_rate: 0.0005
weight_decay: 0
patience: 5
shuffle: true

# eval
eval_batch_size: 256
monitor_metrics: ['Micro-Precision', 'Micro-Recall', 'Micro-F1', 'Macro-F1', 'Another-Macro-F1', 'P@1', 'P@3', 'P@5']
val_metric: Macro-F1

# model
model_name: KimCNN
network_config:
  embed_dropout: 0.2
  encoder_dropout: 0.2
  filter_sizes: [2, 4, 8]
  num_filter_per_size: 128 # filter channels

# pretrained vocab / embeddings
embed_file: glove.6B.300d
