# data
data_dir: data/rcv1
data_name: rcv1
min_vocab_freq: 1
max_seq_length: 500
fixed_length: True

# train
#seed: 1337
epochs: 50
batch_size: 64
optimizer: adam
learning_rate: 0.0005099137446356937
weight_decay: 0
patience: 5

# eval
eval_batch_size: 256
monitor_metrics: [P@1, P@3, P@5]
val_metric: P@1

# model
model_name: XMLCNN
num_filter_per_size: 128 # filter channels
pool_size: 2
filter_sizes: [2, 4, 8]
hidden_dim: 512
dropout: 0.5
dropout2: 0.5

# pretrained vocab / embeddings
embed_file: glove.6B.300d
