# data
data_dir: data/MIMIC-50
data_name: MIMIC-50
min_vocab_freq: 3
max_seq_length: 2500
include_test_labels: true

# train
seed: 1337
epochs: 100
batch_size: 8
optimizer: adam
learning_rate: 0.0003
weight_decay: 0
patience: 10
shuffle: true

# eval
eval_batch_size: 1
monitor_metrics: ['Micro-F1', 'Macro-F1', 'Another-Macro-F1', 'P@1', 'P@3', 'P@5']
val_metric: P@5

# model
model_name: CBiGRULWAN
init_weight: kaiming_uniform
network_config:
  embed_dropout: 0.
  encoder_dropout: 0.1
  rnn_dim: 100
  rnn_layers: 2

# pretrained vocab / embeddings
vocab_file: data/MIMIC-50/vocab.csv
embed_file: data/MIMIC-50/processed_full.embed
normalize_embed: true
label_file: data/MIMIC-50/ICD9_descriptions.txt
