# https://github.com/jamesmullenbach/caml-mimic/blob/master/predictions/CAML_mimic3_50/train_new_model.sh
# data
training_file: data/MIMIC-50/train.txt
val_file: data/MIMIC-50/valid.txt
test_file: data/MIMIC-50/test.txt
data_name: MIMIC-50
min_vocab_freq: 3
max_seq_length: 2500
# We follow caml-mimic that includes labels in both training and test datasets.
include_test_labels: true
# Follow https://github.com/jamesmullenbach/caml-mimic/blob/master/datasets.py#L45
# to remove training and validation instances that have no labels.
remove_no_label_data: true

# train
seed: 1337
epochs: 200
batch_size: 16
optimizer: adam
learning_rate: 0.0001
weight_decay: 0
patience: 10
shuffle: false

# eval
eval_batch_size: 1
monitor_metrics: ['Micro-F1', 'Macro-F1', 'Another-Macro-F1', 'P@1', 'P@3', 'P@5']
val_metric: P@5

# model
model_name: CAML
init_weight: null
network_config:
  embed_dropout: 0.2
  filter_sizes: [10]
  num_filter_per_size: 50

# pretrained vocab / embeddings
vocab_file: data/MIMIC-50/vocab.csv
embed_file: data/MIMIC-50/processed_full.embed
normalize_embed: true
