# data
data_dir: data/MIMIC-50
data_name: MIMIC-50
min_vocab_freq: 3
max_seq_length: 2500
include_test_labels: true

# train
seed: 1337
epochs: 200
batch_size: 16
optimizer: adam
learning_rate: 0.0001
weight_decay: 0
patience: 10
shuffle: true

# eval
eval_batch_size: 1
monitor_metrics: ['Micro-F1', 'Macro-F1', 'Another-Macro-F1', 'P@1', 'P@3', 'P@5', 'RP@5', 'nDCG@5']
val_metric: P@5

# model
model_name: ZeroTCNN
init_weight: xavier_uniform
network_config:
  embed_dropout: 0.4
  encoder_dropout: 0.2
  filter_sizes: [4]
  num_filter_per_size: 1024 # filter channels
  label_num_filter: 512 # filter channels
  activation: tanh

# pretrained vocab / embeddings
vocab_file: data/MIMIC-50/vocab.csv
embed_file: data/MIMIC-50/processed_full.embed
normalize_embed: true
label_file: data/MIMIC-50/ICD9CM.txt
load_label_text: true
