# data
data_dir: data/AmazonCat-13K
data_name: AmazonCat-13K
min_vocab_freq: 1
max_seq_length: 500
include_test_labels: true

# train
seed: 1337
epochs: 50
batch_size: 64
optimizer: adam
learning_rate: 0.0003
weight_decay: 0
patience: 10
shuffle: true

# eval
eval_batch_size: 256
monitor_metrics: ['Micro-F1', 'Macro-F1', 'Another-Macro-F1', 'P@1', 'P@5', 'RP@5']
val_metric: RP@5

# model
model_name: BiGRULWAN
init_weight: kaiming_uniform
network_config:
  embed_dropout: 0.2
  encoder_dropout: 0.2
  rnn_dim: 512
  rnn_layers: 1

# pretrained vocab / embeddings
embed_file: glove.6B.200d
