# This config only serves as an example as it is not tuned by hyper-parameter search.
# data
training_file: data/EUR-Lex-57k/train.txt
val_file: data/EUR-Lex-57k/valid.txt
test_file: data/EUR-Lex-57k/test.txt
data_name: EUR-Lex-57k
min_vocab_freq: 1
max_seq_length: 512
include_test_labels: true
add_special_tokens: true

# train
seed: 1337
epochs: 15
batch_size: 8
optimizer: adamw
learning_rate: 0.00005
weight_decay: 0.001
patience: 5

# eval
eval_batch_size: 8
monitor_metrics: ['Micro-F1', 'Macro-F1', 'Another-Macro-F1', 'P@1', 'P@5', 'RP@5', 'nDCG@5']
val_metric: RP@5

# model
model_name: BERT
init_weight: null
network_config:
  encoder_hidden_dropout: 0.1
  lm_weight: bert-base-uncased
  lm_window: 512

# pretrained vocab / embeddings
embed_file: null
