# data
data_dir: data/EUR-Lex-57k
data_name: EUR-Lex-57k
min_vocab_freq: 1
max_seq_length: 500

# train
seed: 1337
epochs: 100
batch_size: 16
optimizer: adam
learning_rate: 0.0001
weight_decay: 0
patience: 10

# eval
eval_batch_size: 16
monitor_metrics: ['Micro-F1', 'Macro-F1', 'Another-Macro-F1', 'P@1', 'P@5', 'RP@5', 'nDCG@5']
val_metric: RP@5

# model
model_name: ZeroSCNN
init_weight: xavier_uniform
network_config:
  embed_dropout: 0.4
  encoder_dropout: 0
  filter_sizes: [8]
  num_filter_per_size: 2048
  activation: tanh

# pretrained vocab / embeddings
embed_file: glove.6B.200d
label_file: data/EUR-Lex-57k/EURLEX57K_label_descriptions.txt
load_label_text: true
