# data
data_dir: data/MIMIC
data_name: MIMIC
min_vocab_freq: 3
max_seq_length: 2500
include_test_labels: true

# train
seed: 1337
epochs: 100
batch_size: 8
optimizer: adam
learning_rate: 0.0001
weight_decay: 0
patience: 10
shuffle: true

# eval
eval_batch_size: 1
monitor_metrics: ['Micro-F1', 'Macro-F1', 'Another-Macro-F1', 'P@8', 'P@15', 'RP@8', 'RP@15', 'nDCG@15']
val_metric: RP@15

# model
model_name: ZeroTCNN
init_weight: xavier_uniform
network_config:
  embed_dropout: 0.4
  encoder_dropout: 0.2
  filter_sizes: [10]
  num_filter_per_size: 2048 # filter channels
  label_num_filter: 1024 # filter channels
  activation: tanh

# pretrained vocab / embeddings
vocab_file: data/MIMIC/vocab.csv
embed_file: data/MIMIC/processed_full.embed
normalize_embed: true
label_file: data/MIMIC/ICD9CM_aug.txt
load_label_text: true
