# data
data_dir: data/EUR-Lex
data_name: EUR-Lex
min_vocab_freq: 1
max_seq_length: 500

# train
# seed: 1337
epochs: 50
batch_size: 64
optimizer: adam
learning_rate: 0.0005
weight_decay: 0
patience: 5

# eval
eval_batch_size: 256
monitor_metrics: [P@1, P@3, P@5]
val_metric: P@1

# model
model_name: XMLCNN
network_config:
  dropout: 0.2
  dropout2: 0.2
  filter_sizes: [2, 4, 8]
  hidden_dim: 512
  num_filter_per_size: 256 # filter channels
  num_pool: 2

# pretrained vocab / embeddings
embed_file: glove.6B.300d
